[2022-06-18 08:11:41,065] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: simple_etl_dag.run_etl_task manual__2022-06-18T08:11:37.599866+00:00 [queued]>
[2022-06-18 08:11:41,122] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: simple_etl_dag.run_etl_task manual__2022-06-18T08:11:37.599866+00:00 [queued]>
[2022-06-18 08:11:41,124] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 08:11:41,125] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-06-18 08:11:41,126] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 08:11:41,180] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2022-06-18 08:11:37.599866+00:00
[2022-06-18 08:11:41,190] {standard_task_runner.py:52} INFO - Started process 3227 to run task
[2022-06-18 08:11:41,200] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'simple_etl_dag', 'run_etl_task', 'manual__2022-06-18T08:11:37.599866+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/simple_etl.py', '--cfg-path', '/tmp/tmpsbheetdy', '--error-file', '/tmp/tmpdgv1ie4l']
[2022-06-18 08:11:41,203] {standard_task_runner.py:77} INFO - Job 6: Subtask run_etl_task
[2022-06-18 08:11:41,436] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_etl_dag.run_etl_task manual__2022-06-18T08:11:37.599866+00:00 [running]> on host b7a0af5ee6a4
[2022-06-18 08:11:41,738] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=simple_etl_dag
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T08:11:37.599866+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T08:11:37.599866+00:00
[2022-06-18 08:11:41,746] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2022-06-18 08:11:41.745038+00:00
[2022-06-18 08:11:41,749] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2022-06-18 08:11:41.748956+00:00
[2022-06-18 08:11:41,751] {logging_mixin.py:109} INFO - Connecting to DB
[2022-06-18 08:11:41,778] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2022-06-18 08:11:41.748956+00:00
[2022-06-18 08:11:41,781] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2022-06-18 08:11:41.781275+00:00
[2022-06-18 08:11:41,783] {logging_mixin.py:109} INFO - Reading dataset from https://gist.githubusercontent.com/mmphego/
5b6fc4d6dc3c8fba4fce9d994a2fe16b/raw/ab5df0e76812e13df5b31e466a5fb787fac0599a/wine_quality.csv
[2022-06-18 08:11:41,804] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/simple_etl.py", line 30, in inner
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/simple_etl.py", line 92, in etl
    raw_df = extract(DATASET_URL)
  File "/opt/airflow/dags/simple_etl.py", line 30, in inner
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/simple_etl.py", line 50, in extract
    df = pd.read_csv(dataset_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1292, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.7/http/client.py", line 1126, in putrequest
    self._validate_path(url)
  File "/usr/local/lib/python3.7/http/client.py", line 1226, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/mmphego/\n5b6fc4d6dc3c8fba4fce9d994a2fe16b/raw/ab5df0e76812e13df5b31e466a5fb787fac0599a/wine_quality.csv' (found at least '\n')
[2022-06-18 08:11:41,893] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=simple_etl_dag, task_id=run_etl_task, execution_date=20220618T081137, start_date=20220618T081141, end_date=20220618T081141
[2022-06-18 08:11:42,000] {standard_task_runner.py:92} ERROR - Failed to execute job 6 for task run_etl_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/simple_etl.py", line 30, in inner
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/simple_etl.py", line 92, in etl
    raw_df = extract(DATASET_URL)
  File "/opt/airflow/dags/simple_etl.py", line 30, in inner
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/simple_etl.py", line 50, in extract
    df = pd.read_csv(dataset_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1292, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.7/http/client.py", line 1126, in putrequest
    self._validate_path(url)
  File "/usr/local/lib/python3.7/http/client.py", line 1226, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/mmphego/\n5b6fc4d6dc3c8fba4fce9d994a2fe16b/raw/ab5df0e76812e13df5b31e466a5fb787fac0599a/wine_quality.csv' (found at least '\n')
[2022-06-18 08:11:42,069] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-18 08:11:42,217] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
